#!/bin/bash 

links=(
#scrollback
	"https://st.suckless.org/patches/scrollback/st-scrollback-20190331-21367a0.diff"	
	"https://st.suckless.org/patches/scrollback/st-scrollback-mouse-20191024-a2c479c.diff"
	"https://st.suckless.org/patches/scrollback/st-scrollback-mouse-altscreen-20191024-a2c479c.diff"
	#"https://st.suckless.org/patches/scrollback/st-scrollback-mouse-increment-0.8.2.diff"
#solarized colorscheme 
	"https://st.suckless.org/patches/solarized/st-no_bold_colors-20170623-b331da5.diff"
	"https://st.suckless.org/patches/solarized/st-solarized-dark-20180411-041912a.diff"
)

TEMP_DIR=temp
mkdir $TEMP_DIR

for patch_link in  ${links[*]}
do
	patch_name=$(echo $patch_link | grep -oEe "\b/st.+\.diff\b")
	patch_name=${patch_name:1}

	curl $patch_link -o "$TEMP_DIR/$patch_name"
	patch -i "$TEMP_DIR/$patch_name"

done

rm -rf $TEMP_DIR
